# 使いたいrubyのバージョン
ARG RUBY_VERSION=ruby:3.3.1
# 使いたいnodeのversion
ARG NODE_VERSION=20

#ここから下と上は別スコープ

#ベースイメージの指定
FROM $RUBY_VERSION
#buildの際に指定できる引数を指定
ARG RUBY_VERSION
ARG NODE_VERSION
#言語、時刻設定
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo
#Node.jsとYarnをインストールするために行われる一連の操作
RUN apt-get update -qq \
&& apt-get install -y ca-certificates curl gnupg \
&& mkdir -p /etc/apt/keyrings \
&& curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
&& NODE_MAJOR=20 \
&& echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
&& wget --quiet -O - /tmp/pubkey.gpg https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
&& echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
#パッケージのインストール
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs yarn vim
#作業ディレクトリの作成・設定
RUN mkdir /kyo_tag
WORKDIR /kyo_tag
#依存関係管理ツールのインストール
RUN gem install bundler
COPY Gemfile /kyo_tag/Gemfile
COPY Gemfile.lock /kyo_tag/Gemfile.lock
COPY yarn.lock /kyo_tag/yarn.lock
RUN bundle install
RUN yarn install
#ローカルのファイルをコンテナ内にコピーする
COPY . /kyo_tag